version: "3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db

  db:
    image: mongo
    ports:
        - "27017:27017"

  lb:
    image: dockercloud/haproxy
    links:
     - app
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
